### ISSUE TITLE
打扰了，请问怎么 qpt 打包

### ISSUE THREAD

**Issue by NewBugger** [PantsuDango/DangoOCR#5]
```cmd
D:\a\DangoOCR\DangoOCR>python -m pip install qpt 
Collecting qpt
  Downloading QPT-1.0b4.dev[6](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:7)-py3-none-any.whl (525 kB)
     -------------------------------------- 526.0/526.0 kB 6.6 MB/s eta 0:00:00
Collecting pefile
  Downloading pefile-2022.5.30.tar.gz ([7](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:8)2 kB)
     ---------------------------------------- 72.9/72.9 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: click in c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages (from qpt) ([8](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:9).1.3)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pillow
  Downloading Pillow-[9](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:10).3.0-cp39-cp39-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 26.4 MB/s eta 0:00:00
Collecting wget
  Downloading wget-3.2.zip ([10](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:11) kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pip>=22.1.1 in c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages (from qpt) (22.3)
Requirement already satisfied: colorama in c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages (from click->qpt) (0.4.6)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     ------------------------------------- 829.2/829.2 kB 17.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Installing collected packages: wget, toml, pillow, future, pefile, qpt
  DEPRECATION: wget is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for wget: started
  Running setup.py install for wget: finished with status 'done'
  DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for future: started
  Running setup.py install for future: finished with status 'done'
  DEPRECATION: pefile is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pefile: started
  Running setup.py install for pefile: finished with status 'done'
Successfully installed future-0.18.2 pefile-2022.5.30 pillow-9.3.0 qpt-1.0b4.dev6 toml-0.10.2 wget-3.2

Notice:  A new release of pip available: 22.3 -> 22.3.1
Notice:  To update, run: python.exe -m pip install --upgrade pip

D:\a\DangoOCR\DangoOCR>chcp 65001 
Active code page: 65001

D:\a\DangoOCR\DangoOCR>qpt.exe -r -f ./ -p ./app.py -s ./qpt_out/ -h False 
\u2192[2022-[11](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:12)-20 07:36:24,843] [DEBUG] | \u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b\uff1aWindows
\u2192[2022-11-20 07:36:24,843] [DEBUG] | \u64cd\u4f5c\u7cfb\u7edf\u4f4d\u6570\uff1aAMD64
Warning: 22-11-20 07:36:24,843] [WARNING] | C:\Users\RUNNER~1\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6\u4e2d ~ \u5b57\u7b26\u4f1a\u53ef\u80fd\u5f71\u54cd\u4f7f\u7528\u3002
Warning: 22-11-20 07:36:24,843] [WARNING] | \u5f53\u524d\u7cfb\u7edf\u7684\u7528\u6237\u540d\u4e2d\u5305\u542b\u4e2d\u6587/\u7a7a\u683c\u7b49\u53ef\u80fd\u4f1a\u5bf9\u7a0b\u5e8f\u9020\u6210\u5f02\u5e38\u7684\u5b57\u7b26\uff0c\u73b0\u5df2\u9ed8\u8ba4QPT\u4e34\u65f6\u76ee\u5f55\u4e3aC:/q_tmp
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\qpt.exe\__main__.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 2356, in handle_parse_result
    value, source = self.consume_value(ctx, opts)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 2919, in consume_value
    value = self.prompt_for_value(ctx)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 2842, in prompt_for_value
    return prompt(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\termui.py", line 139, in prompt_func
    echo(text.rstrip(" "), nl=False, err=err)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\utils.py", line 299, in echo
    file.write(out)  # type: ignore
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\encodings\cp[12](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:13)52.py", line [19](https://github.com/newbuggerorg1/DangoOCR/actions/runs/3507008102/jobs/5874415216#step:4:20), in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>
Error: Process completed with exit code 1.
```

**Comment by PantsuDango** [comment]
qpt的打包问题可以直接到qpt的官方下发issues，作者还有群可以加1128826410

**Comment by PantsuDango** [comment]
qpt的打包问题可以直接到 [QPT](https://github.com/GT-ZhangAcer/QPT) 的官方下发issues，作者还有群可以加1128826410

**Comment by NewBugger** [comment]
> qpt的打包问题可以直接到 [QPT](https://github.com/GT-ZhangAcer/QPT) 的官方下发issues，作者还有群可以加1128826410

好的，这个不是本项目的问题是吧

**Comment by PantsuDango** [comment]
是的，这个让QPT官方答复会好点~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





  
qpt的打包问题可以直接到 QPT 的官方下发issues，作者还有群可以加1128826410
  
好的，这个不是本项目的问题是吧

**Comment by NewBugger** [comment]
还是请问下使用指令 qpt.exe -f .\ -p .\app.py -r auto -s .\qpt_out -h False 就应该能打包出来吗，总是遇到报错 u82e5\u5728\u6267\u884cEXE\u65f6\u63d0\u793a:ImportError: No module named xxx \u62a5\u9519\u4fe1\u6

**Comment by PantsuDango** [comment]
这边建议使用QPT官方的编写脚本的方式打包，我自己也是这样的。
然后找不到模块的话，要检查一下requirements.txt文件是否写入了该模块，也可以直接将依赖包从python路径里复制到打包根目录下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





 
还是请问下使用指令 qpt.exe -f .\ -p .\app.py -r auto -s .\qpt_out -h False 就应该能打包出来吗，总是遇到报错 u82e5\u5728\u6267\u884cEXE\u65f6\u63d0\u793a:ImportError: No module named xxx \u62a5\u9519\u4fe1\u6

**Comment by NewBugger** [comment]
>> 这边建议使用QPT官方的编写脚本的方式打包，我自己也是这样的。

官方提供的两种使用方式应该是一样效果，那么我直接使用上述命令 应该没有使用本项目上的错误 吗

**Comment by PantsuDango** [comment]
我不确定，这个得问QPT官方了，直接脚本会更方便快捷一点，你先试试，另外注意依赖文件的完整性，不行就把包复制过来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





   
这边建议使用QPT官方的编写脚本的方式打包，我自己也是这样的。
   
官方提供的两种使用方式应该是一样效果，那么我直接使用上述命令 应该没有使用本项目上的错误 吗

**Comment by NewBugger** [comment]
>> 另外注意依赖文件的完整性，不行就把包复制过来

因为本项目里并没有 requirements.txt 文件，依赖这方面我并不知道应该怎么办，就只是直接执行了 qpt 指令

**Comment by PantsuDango** [comment]
不是的，我指的 requirements.txt 是QPT开始执行打包后自动生成的那个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





   
另外注意依赖文件的完整性，不行就把包复制过来
   
因为本项目里并没有 requirements.txt 文件，依赖这方面我并不知道应该怎么办，就只是直接执行了 qpt 指令

**Comment by NewBugger** [comment]
> 不是的，我指的 requirements.txt 是QPT开始执行打包后自动生成的那个

那请问该怎么办

**Comment by PantsuDango** [comment]
可以尝试一下官方用脚本的方式打包，其次检查一下QPT打包后生成的那个&nbsp;requirements.txt 文件的依赖是否完整，也可以直接把缺失的包丢到编译的目录里


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





  
不是的，我指的 requirements.txt 是QPT开始执行打包后自动生成的那个
  
那请问该怎么办

**Comment by NewBugger** [comment]
> 可以尝试一下官方用脚本的方式打包，其次检查一下QPT打包后生成的那个&nbsp;requirements.txt 文件的依赖是否完整，也可以直接把缺失的包丢到编译的目录里
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PantsuDango/DangoOCR" ***@***.***&gt;; 发送时间:&nbsp;2022年11月20日(星期天) 晚上10:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5) 不是的，我指的 requirements.txt 是QPT开始执行打包后自动生成的那个 那请问该怎么办 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢回复。使用脚本后遇到相同的问题无变化；QPT打包后生成的那个 requirements.txt 稍等我看下它；至于缺失的依赖项我就不知道是缺了什么，“ImportError: No module named xxx” 没有输出名字

**Comment by NewBugger** [comment]
> QPT打包后生成的那个 requirements.txt 稍等我看下它

没有 requirements.txt 文件，有 requirements_with_opt.txt

```
D:\a\DangoOCR\DangoOCR>type .\requirements_with_opt.txt 
# Here is the list of packages automatically derived by QPT
# you can ignore the dependent packages in the main package and only care about the main package
# For example, you need to install paddlepaddle and pillow, because paddlepaddle relies on pillow, so you only need to install paddlepaddle.
# ---------------------------------------------------------------------
# QPT Home:        https://github.com/GT-ZhangAcer/QPT
# ---------------------------------------------------------------------
# 
# -------------Mainly depends on package analysis results--------------

qpt==1.0b4.dev6
userpath==1.8.0

# ----------------------Ignored dependent packages---------------------
#pipx==1.1.0

# ----------------------Ignored sub dependent packages---------------------

# -----Dependencies of qpt
#pefile
#wget
#pillow
#click
#toml
#pip>=22.1.1

# -----Dependencies of userpath
#click
```

**Comment by PantsuDango** [comment]
可以直接来QQ群1128826410




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/DangoOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/DangoOCR] 打扰了，请问怎么 qpt 打包 (Issue #5)





  
QPT打包后生成的那个 requirements.txt 稍等我看下它
  
没有 requirements.txt 文件，有 requirements_with_opt.txt
 D:\a\DangoOCR\DangoOCR&gt;type .\requirements_with_opt.txt  # Here is the list of packages automatically derived by QPT # you can ignore the dependent packages in the main package and only care about the main package # For example, you need to install paddlepaddle and pillow, because paddlepaddle relies on pillow, so you only need to install paddlepaddle. # --------------------------------------------------------------------- # QPT Home:        https://github.com/GT-ZhangAcer/QPT # --------------------------------------------------------------------- #  # -------------Mainly depends on package analysis results-------------- qpt==1.0b4.dev6 userpath==1.8.0 # ----------------------Ignored dependent packages--------------------- #pipx==1.1.0 # ----------------------Ignored sub dependent packages--------------------- # -----Dependencies of qpt #pefile #wget #pillow #click #toml #pip&gt;=22.1.1 # -----Dependencies of userpath #click
